export const SUPPORTED_MARKDOWN_SPECIMEN = [
  '# Heading one',
  '',
  'Paragraph one with **strong** and *emphasis*.',
  '',
  '## Heading two',
  '',
  '- first',
  '- second',
  '',
  '1. ordered first',
  '2. ordered second',
  '',
  '> quoted',
  '',
  '`inline`',
  '',
  '```',
  'block code',
  '```',
  '',
  '[safe link](https://example.com)',
  '',
  '| Column A | Column B |',
  '| :-- | --: |',
  '| Alpha | 1 |',
  '| Beta | 2 |',
  '',
  '---',
  '',
  '![Worldhaven Frosthaven divider](https://any2cards.github.io/worldhaven/images/art/frosthaven/card-dividers/fh-available-pets.png)',
].join('\n');

export const UNSUPPORTED_MARKDOWN_SPECIMEN = [
  'Unsupported examples should stay inert instead of half-rendering.',
  '',
  '<script>alert("nope")</script>',
  '',
  '[unsafe link](http://example.com)',
  '',
  '![alt](http://example.com/image.png)',
].join('\n');

export const SUPPORTED_MARKDOWN_FEATURES = [
  'Headings',
  'Paragraphs',
  'Strong emphasis',
  'Emphasis',
  'Unordered lists',
  'Ordered lists',
  'Blockquotes',
  'Inline code',
  'Fenced code blocks',
  'Safe HTTPS links',
  'Tables',
  'Horizontal rules',
  'Allowlisted HTTPS images',
] as const;

export const UNSUPPORTED_MARKDOWN_FEATURES = [
  'Raw HTML',
  'Non-HTTPS links',
  'Non-HTTPS images',
  'Non-allowlisted HTTPS images',
] as const;
